In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.8.1+cu101'

In [4]:
arr=np.array(range(5))

In [5]:
arr

array([0, 1, 2, 3, 4])

In [6]:
x=torch.from_numpy(arr)

In [7]:
x

tensor([0, 1, 2, 3, 4])

In [8]:
type(x)

torch.Tensor

In [9]:
torch.as_tensor(arr)

tensor([0, 1, 2, 3, 4])

In [10]:
x.dtype

torch.int64

In [11]:
arr2d=np.arange(0.0,12.0).reshape(4,3)

In [12]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [13]:
y=torch.from_numpy(arr2d)

In [14]:
y

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [15]:
arr[0]=100

In [16]:
arr

array([100,   1,   2,   3,   4])

In [17]:
x

tensor([100,   1,   2,   3,   4])

In [18]:
new_arr=np.array(range(10))

In [19]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_tensor=torch.tensor(new_arr)

In [21]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
new_arr[0]=100

In [23]:
new_arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [24]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a=np.array([1,2,3])

In [26]:
torch.tensor(a)

tensor([1, 2, 3])

In [27]:
torch.Tensor(a)

tensor([1., 2., 3.])

In [28]:
torch.empty(5,10)

tensor([[-4.8034e-09,  3.0669e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  3.5733e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  3.5733e-43,  0.0000e+00,  1.4013e-45,  0.0000e+00],
        [-4.8086e-09,  3.0669e-41, -4.8086e-09,  3.0669e-41,  3.5733e-43,
          0.0000e+00,  6.7262e-44,  0.0000e+00, -4.8087e-09,  3.0669e-41],
        [-4.8087e-09,  3.0669e-41,  3.5733e-43,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 3.5733e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  3.5733e-43,  0.0000e+00]])

In [29]:
torch.empty(2,2)

tensor([[-5.9136e-08,  3.0669e-41],
        [ 1.4013e-45,  0.0000e+00]])

In [30]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [31]:
torch.zeros(4,3,dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [32]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [33]:
torch.arange(0,20,2).reshape(5,2)

tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14],
        [16, 18]])

In [34]:
torch.linspace(0,20,14).reshape(2,7)

tensor([[ 0.0000,  1.5385,  3.0769,  4.6154,  6.1538,  7.6923,  9.2308],
        [10.7692, 12.3077, 13.8462, 15.3846, 16.9231, 18.4615, 20.0000]])

In [35]:
b=torch.tensor([1,2,3])

In [36]:
b.dtype

torch.int64

In [37]:
c=b.type(torch.int32)

In [38]:
c

tensor([1, 2, 3], dtype=torch.int32)

In [39]:
torch.rand(4,3)

tensor([[0.8405, 0.8245, 0.3156],
        [0.0465, 0.1226, 0.4438],
        [0.9178, 0.1255, 0.2129],
        [0.6728, 0.5871, 0.2815]])

In [40]:
torch.randn(4,3)

tensor([[ 1.1180,  0.4080, -1.5188],
        [ 0.9320,  1.3737,  0.4295],
        [-0.4372, -0.0724,  0.8149],
        [-0.0922, -1.9730, -1.0426]])

In [41]:
torch.randint(low=0,high=10,size=(5,5))

tensor([[5, 7, 5, 4, 1],
        [6, 9, 3, 5, 1],
        [8, 6, 1, 5, 0],
        [8, 5, 6, 0, 0],
        [1, 2, 7, 9, 3]])

In [42]:
x=torch.zeros(5,3)

In [43]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [44]:
torch.rand_like(x)

tensor([[0.3541, 0.4665, 0.3074],
        [0.5399, 0.8579, 0.6178],
        [0.7182, 0.2518, 0.8918],
        [0.7250, 0.7775, 0.1347],
        [0.8631, 0.2287, 0.8383]])

In [45]:
torch.randn_like(x)

tensor([[-0.4179,  0.5514,  1.1401],
        [-0.6921, -1.0292, -0.0758],
        [-0.4881,  2.0331, -0.7531],
        [ 0.1442,  0.1219, -0.6000],
        [-0.7178, -0.4752,  0.9557]])

In [46]:
torch.randint_like(x,0,10)

tensor([[9., 4., 2.],
        [3., 6., 5.],
        [2., 6., 5.],
        [0., 5., 4.],
        [3., 9., 2.]])

In [47]:
torch.manual_seed(42)

In [48]:
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [49]:
x=torch.arange(6).reshape(3,2)

In [50]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [51]:
x[1,1]

tensor(3)

In [52]:
x[0,1]

tensor(1)

In [53]:
x[:,1]

tensor([1, 3, 5])

In [54]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [55]:
x=torch.arange(10)

In [56]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [58]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
z=x.view(2,5)

In [60]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [61]:
x[0]=9999

In [62]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [63]:
x.view(2,-1)

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [64]:
x.view(-1,2)

tensor([[9999,    1],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])

In [65]:
x.view(-1,10)

tensor([[9999,    1,    2,    3,    4,    5,    6,    7,    8,    9]])

In [66]:
a,b=torch.Tensor([1,2,3]),torch.Tensor([4,5,6])

In [67]:
a+b

tensor([5., 7., 9.])

In [68]:
a.add(b)

tensor([5., 7., 9.])

In [69]:
a

tensor([1., 2., 3.])

In [70]:
a.add_(b)

tensor([5., 7., 9.])

In [71]:
a

tensor([5., 7., 9.])

In [72]:
a,b=torch.Tensor([1,2,3]),torch.Tensor([4,5,6])

In [73]:
a*b

tensor([ 4., 10., 18.])

In [74]:
a,b=torch.randint(0,10,(3,3)),torch.randint(0,10,(3,3))

In [75]:
a

tensor([[0, 4, 0],
        [3, 8, 4],
        [0, 4, 1]])

In [76]:
b

tensor([[2, 5, 5],
        [7, 6, 9],
        [6, 3, 1]])

In [77]:
a.mul(b)

tensor([[ 0, 20,  0],
        [21, 48, 36],
        [ 0, 12,  1]])

In [78]:
a*b

tensor([[ 0, 20,  0],
        [21, 48, 36],
        [ 0, 12,  1]])

In [79]:
torch.mm(a,b)

tensor([[28, 24, 36],
        [86, 75, 91],
        [34, 27, 37]])

In [80]:
a @ b

tensor([[28, 24, 36],
        [86, 75, 91],
        [34, 27, 37]])

In [81]:
x=torch.tensor([2.,3.,4.,5.])

In [82]:
x.norm()

tensor(7.3485)

In [83]:
x.numel()

4