In [1]:
import torch

In [2]:
x=torch.tensor(2.0,requires_grad=True)

In [3]:
x

tensor(2., requires_grad=True)

In [4]:
y=2*x**4+x**3+3*x**2+5*x+1

In [5]:
print(y)
# x=2 in y eq

tensor(63., grad_fn=<AddBackward0>)


In [6]:
type(y)

torch.Tensor

In [7]:
y.backward()

In [8]:
x.grad
# x=2 in y' eq

tensor(93.)

In [14]:
x=torch.tensor([[1.,2.,3.],[3.,2.,1.]],requires_grad=True)

In [15]:
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [16]:
y = 3*x + 2 

In [17]:
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [18]:
z = 2*y**2

In [19]:
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [20]:
out = z.mean()

In [21]:
out

tensor(140., grad_fn=<MeanBackward0>)

In [22]:
out.backward()

In [23]:
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])